# Generated by Django 5.0.4 on 2024-04-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playdate', '0003_alter_playdate_options_alter_playdate_suitable_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playdate',
            options={'ordering': ['date']},
        ),
    ]
