# Generated by Django 5.0.4 on 2024-04-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playdate', '0004_alter_playdate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playdate',
            options={'ordering': ['created_at']},
        ),
    ]
