# Generated by Django 5.0.4 on 2024-04-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-11T08:24:55.271437Z'),
            preserve_default=False,
        ),
    ]
